bank.core.base-url=http://localhost:8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

# Resilience4j - Circuit Breaker Bank Core
resilience4j.circuitbreaker.instances.bankCore.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.bankCore.sliding-window-size=5
resilience4j.circuitbreaker.instances.bankCore.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.bankCore.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.bankCore.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.bankCore.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.bankCore.automatic-transition-from-open-to-half-open-enabled=true